allprojects {
    version = '1.0-SNAPSHOT'
    group = 'at.gl1tchxd'

    repositories {
        mavenCentral()
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
        maven { url 'https://jitpack.io' }
    }
}

ext {
    gdxVersion = '1.12.1'
    kryonetVersion = '2.22.0-RC1'
}

subprojects {
    apply plugin: 'java-library'

    java {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}